empty_upstream:
    name: backend
    members: []
    upstream_fail_timeout: 10s

empty_proxy:
    proxy: ~
    proxy_redirect: off
    proxy_read_timeout: 90
    proxy_connect_timeout: 90
    proxy_cache: ~
    proxy_cache_valid: ~
    proxy_method: ~
    proxy_set_body: ~

empty_vhost:
    server_name: ~
    server_aliases: []
    www_root: /var/www/REPLACE_ME
    listen_port: 80
    ssl: false
    ssl_port: 443
    ssl_cert: ''
    ssl_key: ''
    rewrite_to_https: 0
    spdy: 0
    client_max_body_size: '1m'
    locations: []

empty_location:
    www_root: /var/www/REPLACE_ME
    location: '~ \.php$'
    autoindex: 0
    internal: false
    index_files:
        - index.php
    try_files:
        - $uri
        - $uri/
    fastcgi: '127.0.0.1:9000'
    fastcgi_index: index.php
    fastcgi_split_path: '^(.+?\.php)(/.*)$'
    fast_cgi_params_extra:
        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
    set:
        - '$path_info $fastcgi_path_info'
    proxy: ~
    proxy_redirect: ~
    proxy_set_header: []

empty_vhost_rewrite:
    when: ~
    regex: ~
    target: ~

empty_location_rewrite:
    when: ~
    regex: ~
    target: ~
