empty_vhost:
    servername: ~
    serveraliases: []
    docroot: /var/www/REPLACE_ME
    port: 80
    setenvif:
        - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
    custom_fragment: ~
    directories: []
    ssl: 0
    ssl_cert: ~
    ssl_key: ~
    ssl_chain: ~
    ssl_certs_dir: ~

empty_directory:
    provider: directory
    directoryindex: index.php
    path: /var/www/REPLACE_ME
    options:
        - Indexes
        - FollowSymlinks
        - MultiViews
    allow_override:
        - All
    require:
        - all granted
    custom_fragment: ~

empty_files_match:
    provider: filesmatch
    path: '\.php$'
    sethandler: 'proxy:fcgi://127.0.0.1:9000'
    setenv: []
    custom_fragment: ''

empty_rewrite:
    comment: ~
    rewrite_base: ~
    rewrite_cond: []
    rewrite_rule: []

modules:
    - cache
    - cgid
    - dav
    - dav_fs
    - deflate
    - disk_cache
    - expires
    - headers
    - info
    - ldap
    - mime_magic
    - pagespeed
    - proxy_ajp
    - proxy_balancer
    - proxy_fcgi
    - proxy_http
    - proxy
    - rewrite
    - userdir
    - vhost_alias
